variables:
    DOCKER_REGISTRY: 684732954876.dkr.ecr.ap-northeast-2.amazonaws.com
    AWS_DEFAULT_REGION: ap-northeast-2
    APP_NAME: rest-api-server
    APP_TAG: latest
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''

publish:
    stage: build
    image:
        name: amazon/aws-cli
        entrypoint: ['']
    services:
        - docker:dind
    before_script:
        - amazon-linux-extras install docker
        - aws --version
        - docker --version
    script:
        - echo "build docker image"
        - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $DOCKER_REGISTRY
        - docker build --tag $APP_NAME:$APP_TAG .
        - docker tag $APP_NAME:$APP_TAG $DOCKER_REGISTRY/$APP_NAME:$APP_TAG
        - docker push $DOCKER_REGISTRY/$APP_NAME:$APP_TAG
        - aws deploy create-deployment --application-name CD-rest-api --deployment-group-name DG-rest-api --s3-location bucket=s3-eedited-prod-rest-api-code-deploy,key=appspec.yml.zip,bundleType=zip
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
